### PR TITLE
feat: add on click callback

### PR DESCRIPTION
**Pull request by tilman151**
Hey, I recently needed some callbacks from Plotly in FastHTML and I figured your package might be the right place to put it.

I included the JS code in the `plotly_headers` and render a call to it when registering a callback. You can have a look at the example app to see it in action. If what I wrote is acceptable for you I'd add some tests to it before merging. Would adding `playwright` as a dev dependency be okay for you then? I'd like to actually do the click during an end2end test.

### CODE REVIEW

**Comment by CarloLepelaars** [comment]
Hi @tilman151, thank you so much for the contribution! 

The implementation looks great. Adding `playwright` as a dev dependency is ok. Are you familiar with `uv` (`uv add playwright`)? Also feel free to set the version to `0.2.1`.

If you could add some tests and they pass I think we are ready to merge.

**Comment by tilman151** [comment]
Yeah, I'm familiar with uv. Will try to do it tomorrow.

**Comment by tilman151** [comment]
I added the tests to the CI in a separate job because setting up playwright is a time-consuming operation.

On another note: you set up your dev dependencies as an extra. Typically they are added as a [dependency group](https://docs.astral.sh/uv/concepts/projects/dependencies/#development-dependencies) in `uv` so that they are automatically installed when calling `uv sync` but not included in the PyPI build. Up to you.

**Comment by CarloLepelaars** [comment]
Good catch on the dev dependencies! Feel free to add them as a dependency group instead of extras. 

Something failing with `playwright install`?

**Comment by tilman151** [comment]
Ah, yeah. Forgot to deactivate the e2e tests in the test job and forgot to install the extra deps in the e2e job. Let me fix that.

**Comment by tilman151** [comment]
Should run now, hopefully.

**Comment by CarloLepelaars** [comment]
Amazing, thank you! Will release it now for v0.2.1

**Comment by CarloLepelaars** [comment]
Released! 😄 

https://pypi.org/project/fh-plotly

**Comment by tilman151** [comment]
If you want, I can also have a look at the selection callback. Shouldn't be that hard, now that the scaffolding is there.

**Comment by CarloLepelaars** [comment]
> If you want, I can also have a look at the selection callback. Shouldn't be that hard, now that the scaffolding is there.

Great idea! Additional PRs are definitely appreciated.

**Pull request merged**
